### ISSUE TITLE
Feature Request: Mark notes as read.

### ISSUE THREAD

**Issue by jeefy** [kubernetes-sigs/release-notes#77]
The ability to select/mark notes as read might be beneficial to some. It'd require using something like localStorage, but it's a thought worth discussing. :)

**Comment by saschagrunert** [comment]
Sounds good, having it in local storage or a cookie (don't see a reason for that now) could work well with the usage of something like [ngrx-store-localstorage](https://github.com/btroncone/ngrx-store-localstorage). This way we could sync the state easily with the existing architecture.

Some sort of automatic detection if something has been viewed already could be tricky, because clicking a checkbox for every item might be too much for the users, right?

**Comment by jeefy** [comment]
I was thinking they could click on the note's header to highlight it, and have an option in the header (or something) to mark as read. 

If the site detects that they _have_ marked something as read, there would be an option to check (on the left) to "show read notes"

Make sense?

**Comment by saschagrunert** [comment]
Sounds reasonable, later on we could mark them automatically as ready when they appeared a certain amount of time on screen...
